name: tfw.chatapp
description: The tfw messaging app.

# version number + build number
version: 0.1.0+6

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  intl: ^0.16.0
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  built_value: ^7.0.2
  mobx: ^1.0.1
  flutter_mobx: ^1.0.1
  firebase_core: ^0.4.0
  firebase_analytics: ^5.0.1
  firebase_auth: ^0.14.0
  firebase_messaging: ^5.1.6
  cloud_firestore: ^0.12.9
  google_sign_in: ^4.1.1
  flutter_auth_buttons: ^0.5.0
  url_launcher: ^5.1.3

dev_dependencies:
  test: ^1.6.3
  flutter_test:
    sdk: flutter
  build_runner: ^1.7.2
  built_value_generator: ^7.0.9
  mobx_codegen: ^1.0.1

# Flutter config
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
